### ISSUE TITLE
How to use your tool to download *all* the cards?

### ISSUE THREAD

**Issue by Hellisotherpeople** [arvind-balaji/debate-cards#1]
First of all, thank you so much for making this project. 

I've previously experimented with trying to create sequence - sequence models which would automatically underline policy debate evidence. My issue is that I always had trouble parsing each card and getting it into a format outside of .docx. 

It looks like your project could seriously help me in this regards. I'm looking to download a curated list of as many debate cards as I can, and specifically in a format that makes it easy for me to use python to programmatically figure out which part of the card is underlined and which isn't. This was tough when I tried to use pythons tools for reading docx files.

Let me know if you have any advice for me.

**Comment by arvind-balaji** [comment]
Right now there isn't really a way to download the entirety of the parsed data from debate.cards yet, but it's possible to generate the data yourself.

The code for scraping cards out of word docs is completely standalone from the rest of the project and is located at [util/scrape.js](https://github.com/arvind-balaji/debate-cards/blob/master/util/scrape.js). The script processes all the word docs in a directory and uploads them to a mongo database. For reference, [here is the format of a single card document ](https://pastebin.com/raw/TcRZTu6T). The body of the card is stored in the `fullCard` property and the underlined text can be scraped relatively easily using an html parser.

That being said, I definitely think it's important to have easy public access to the data, considering that 
debate.cards is essentially the only source for structured debate evidence data at the moment. A public REST API is something that is in the works, and it would let developers use the parsed data for their own project. I don't have a specific timeline on when the API will be available, but I'm going to leave this issue open until it is.
