### ISSUE TITLE
Indexer setup

### ISSUE THREAD

**Issue by arvind-balaji** [arvind-balaji/debate-cards#17]
Need to decide between Elastic Search and Solr. Planning to test both.

**Comment by D0ugins** [comment]
Is it worth it to sync to the indexer from the code? For simple queries its fine but for more complex and nested queries it would be a pain. Solr supports custom [Data Import Handlers](https://solr.apache.org/guide/6_6/uploading-structured-data-store-data-with-the-data-import-handler.html) and it seems like that can be set up with the [Postgres JDBC Driver](https://jdbc.postgresql.org/) directly from config files. I don't see a similar option for elasticsearch, but something like [pgsync](https://github.com/toluaina/pgsync) wouldn't be that big of a deal to manage if we are using containers.
