### ISSUE TITLE
Running from a flash?

### ISSUE THREAD

**Issue by SteelGraph** [arvind-balaji/debate-cards#6]
I'm relatively green with programming, but if I downloaded a bunch of speech docs to a flash, as well as all of the programs you have listed as required onto a flash/the computer I'd be using this on, would I be able to have it parse cards and search them from those docs?

**Comment by arvind-balaji** [comment]
You'd need to install all the dependencies on the host machine and run it from there. You should still be able to load in files from the flash drive, but this is a fairly slow process.
