### ISSUE TITLE
Updated source code?

### ISSUE THREAD

**Issue by otisdog8** [arvind-balaji/debate-cards#7]
So I'm trying to self host this on my machine, and I've noticed some issues that appear to be caused because the code I have is somehow different from what you're running on your production servers. 
Some example differences:
api.debate.cards returns the card text in the field fullCard, whereas mine returns it in the field card
My instance clears the list of searched cards upon viewing a card (happens on both my and your API backend)
In general I have had to make slight changes to your code to get things to work (like changing the code that generates the solr query) 

Would it be possible for you to update the code that exists (in this repo and the cardDB repo), as well as any config files that might have changed?

**Comment by arvind-balaji** [comment]
The code here is actually ahead of the deployed version - release v1.0.0 (d2b6e31) is the version that's currently in production. 

The frontend repo should be in sync with the live site. So I'm not entirely sure what's causing that issue, I can look into it.
